#!groovy
pipeline {
	agent {
		label 'master'
	}
	tools {
		maven 'maven3'
		jdk 'java8'
	}
	stages {
		stage('Build') {
			steps {
				sh 'mvn clean package'
			}
		}
		stage('Deploy') {
			when {
				branch 'master'
			}
			steps {
				script {
					currentBuild.displayName = "${REVISION}"
				}
				sh 'mvn deploy scm:tag -Drevision=${REVISION}'
			}
		}
	}
}
